services:
  mydung_server:
    build:
      context: .
      dockerfile: ./docker/dockerfile
    container_name: mydung_server
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7  
    container_name: mydung_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: mydung
      MYSQL_USER: mydung
      MYSQL_PASSWORD: mydung  
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql